# PUBLIC ROUTES
[home]
path = "serjeant/home"
match_type = regex
params[page] = "%d"
function = _home
authenticated = true
authentication = user_login
roles[] = JIRA_USER

# ADMIN ROUTES

# API ROUTES

# ADMIN API ROUTES